[[project]]
name = "Formal Group Laws and Stable Homotopy Theory over Compactly Metrizable Groups"
desc = "We extend the theory of complex-oriented cohomology theories to the setting of A-equivariant homotopy theory, where A is a compact metrizable abelian group. We identify the homotopy groups of the A-equivariant complex bordism spectrum with the A-equivariant Lazard ring, and we factor the chromatic character map via geometric fixed points through p-adic equivariant Borel–Lubin–Tate theory."
tags =["equivariant-homotopy-theory", "chromatic-homotopy-theory", "master-thesis"]
links = [
    {name = "pdf", url= "/files/master_thesis_final.pdf"},
]

[[project]]
name = "Algorithmic Computation of Reidemeister Torsion"
desc = "We develop an algorithm that computes the Reidemeister Torsion of the geometric realization of a simplicial set. We compute the Reidemeister Torsions of the Poincare Homology 3-Sphere."
tags = ["computational-topology", "Reidemeister-torsion", "bachelor-thesis"]
links = [
    {name = "pdf", url = "/files/Computation_of_Reidemeister_Torsion.pdf"},
]

# [[project]]
# name = "lorem"
# desc = "Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et!"
# tags = ["nisi", "saepe"]
# links = [
#     {name = "github", url = "https://example.com"},
#     {name = "docs", url = "https://example.com"},
# ]

